version: 2
updates:
  # Bundler dependencies (Ruby gems)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "America/Toronto"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
    open-pull-requests-limit: 5
    reviewers:
      - "Archetypically"
    labels:
      - "dependencies"
      - "bundler"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "America/Toronto"
    groups:
      actions-updates:
        patterns:
          - "*"
    open-pull-requests-limit: 2
    reviewers:
      - "Archetypically"
    labels:
      - "dependencies"
      - "github-actions"
