name: Publish Gem

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to publish (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Extract version from tag
      id: version
      run: |
        # Get tag from either release event or manual input
        if [ "${{ github.event_name }}" = "release" ]; then
          TAG_NAME="${{ github.event.release.tag_name }}"
        else
          TAG_NAME="${{ inputs.tag_name }}"
        fi
        VERSION=${TAG_NAME#v}  # Remove 'v' prefix
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Verify version matches
      run: |
        GEMSPEC_VERSION=$(ruby -r ./lib/activejob/compressible/version.rb -e "puts ActiveJob::Compressible::VERSION")
        RELEASE_VERSION="${{ steps.version.outputs.version }}"

        if [ "$GEMSPEC_VERSION" != "$RELEASE_VERSION" ]; then
          echo "Error: Version mismatch!"
          echo "Gemspec version: $GEMSPEC_VERSION"
          echo "Release version: $RELEASE_VERSION"
          exit 1
        fi

        echo "✅ Version verified: $GEMSPEC_VERSION"

    - name: Build gem with checksum
      run: bundle exec rake build:checksum

    - name: Publish to RubyGems
      run: gem push pkg/activejob-compressible-*.gem

    - name: Annotate publication success
      id: publish_info
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        TAG="${{ steps.version.outputs.tag }}"
        RUBYGEMS_URL="https://rubygems.org/gems/activejob-compressible/versions/$VERSION"
        INSTALL_CMD="gem install activejob-compressible -v $VERSION"

                echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "rubygems_url=$RUBYGEMS_URL" >> $GITHUB_OUTPUT
        echo "install_cmd=$INSTALL_CMD" >> $GITHUB_OUTPUT

        cat >> $GITHUB_STEP_SUMMARY << EOF
        # 🎉 Gem Published Successfully!

        `activejob-compressible` version `$VERSION` has been published to RubyGems.

        ## 📦 Installation
        \`\`\`bash
        $INSTALL_CMD
        \`\`\`

        ## 🔗 Links
        - **RubyGems:** [$RUBYGEMS_URL]($RUBYGEMS_URL)
        - **Git Tag:** \`$TAG\`
        - **GitHub Release:** [View Release](https://github.com/Archetypically/activejob-compressible/releases/tag/$TAG)
        EOF
